### ISSUE TITLE
"test" and it's malware? (NOTE: POSSIBLE MISTAKE?)

### ISSUE THREAD

**Issue by loneicewolf** [APT64/test#1]
check virus total:

beacon.exe  - https://www.virustotal.com/gui/file/c8c49333b61ecc61a22d6fd8c1855f8254078014257150bb840c9ab7d26dcdb2
bind.elf  - https://www.virustotal.com/gui/file/c793f21f60e1d48eb648a6ad053d345354d2a1c729826209dea69660fe7c17e4
run.exe - https://www.virustotal.com/gui/file/946e732a2ea6152102da563d87f7be58cad238aa20cf9df20a0a93e19d856204
svchost.exe - https://www.virustotal.com/gui/file/ec04ada850ae8ce952e86f69953b217a217b263cdeb0c90dde2e278e4e197b4d

also PLEASE NOTE:
@APT64   - you did not include the rsa priv. key?  by mistake right??

**Comment by APT64** [comment]
No, no mistakes. Everything you can see has been collected as samples of malicious code.
